.PHONY loader

all: 
	loader

loader: 
	g++ test_graph_loader.cpp ../../fpga/src/csc_fpga/csc_fpga.cpp -std=c++11 -o loader -I/xilinx/software/Vivado/2018.2/include/ -I/opt/xilinx/software/SDx/2018.2
